-- Add portrait preview URL to videos table
-- Generated by the frame designer feature: stores a face-centred 9:16 JPEG
-- extracted from the best clip after identify_clips completes.
alter table videos add column if not exists portrait_preview_url text;
